x-bot-env-vars: &bot-env-vars # all apps need these
  NODE_ENV: production
  LOG_LEVEL: info

  PB_URL: http://pb:9098
  ADMIN_EMAIL: ${ADMIN_EMAIL:-}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}

  # only for typegen
  PB_TYPEGEN_EMAIL: ${PB_TYPEGEN_EMAIL:-}
  PB_TYPEGEN_PASSWORD: ${PB_TYPEGEN_PASSWORD:-}
  PB_TYPEGEN_URL: ${PB_TYPEGEN_URL:-}

  # clean-db
  PRUNE_ALERT_TIMESPAN_MINUTES: ${PRUNE_ALERT_TIMESPAN_MINUTES:-5}
  DELETE_PER_ITERATION: ${DELETE_PER_ITERATION:-100}

  # alerts-listener
  TELEGRAM_API_ID: ${TELEGRAM_API_ID:-}
  TELEGRAM_API_HASH: ${TELEGRAM_API_HASH:-}
  TELEGRAM_SESSION_STRING: ${TELEGRAM_SESSION_STRING:-}
  TELEGRAM_ALERTS_CHANNEL_ID: ${TELEGRAM_ALERTS_CHANNEL_ID:-}

  # bot
  BOT_TOKEN: ${BOT_TOKEN:-}
  WEBHOOK_DOMAIN: ${WEBHOOK_DOMAIN:-}
  WEBHOOK_PORT: ${WEBHOOK_PORT:-80}
  # WEBHOOK_SECRET_TOKEN: ${WEBHOOK_SECRET_TOKEN:-}
  AUTHOR: ${AUTHOR:-}

x-webapp-env-vars: &webapp-env-vars # webapp
  PORT: ${PORT:-80}

services:
  alerts-listener:
    image: ghcr.io/noamloewenstern/red-alert-bot/apps:dev
    depends_on:
      - pb
    environment:
      <<: *bot-env-vars
      PACKAGE: listener
      COMMAND: start
    restart: unless-stopped

  bot:
    image: ghcr.io/noamloewenstern/red-alert-bot/apps:dev
    depends_on:
      - pb
    environment:
      PACKAGE: bot
      COMMAND: start
      <<: *bot-env-vars
      WEBHOOK_PORT: 80
    ports:
      - 80
    restart: unless-stopped

  webapp-server:
    image: ghcr.io/noamloewenstern/red-alert-bot/apps:dev
    depends_on:
      - pb
    environment:
      <<: *bot-env-vars
      PACKAGE: webapp-server
      COMMAND: start
      PORT: 80
    restart: unless-stopped

  webapp:
    image: ghcr.io/noamloewenstern/red-alert-bot/webapp:dev
    depends_on:
      - webapp-server
    environment:
      <<: *webapp-env-vars
      CADDY_BACKEND_URL: http://webapp-server
      WEBAPP_PORT: 80
    ports:
      - 80
    restart: unless-stopped

  pb:
    image: ghcr.io/noamloewenstern/red-alert-bot/pocketbase:dev
    command: ['/pb/pocketbase', 'serve', '--http=0.0.0.0:9098']
    ports:
      - 9098
    volumes:
      - pb_data:/pb/pb_data
    restart: unless-stopped

volumes:
  pb_data:
