/// <reference path="../pb_data/types.d.ts" />
migrate(
  db => {
    const snapshot = [
      {
        id: '_pb_users_auth_',
        created: '2024-09-13 14:54:50.636Z',
        updated: '2024-09-13 14:54:50.656Z',
        name: 'users',
        type: 'auth',
        system: false,
        schema: [
          {
            system: false,
            id: 'users_name',
            name: 'name',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'users_avatar',
            name: 'avatar',
            type: 'file',
            required: false,
            presentable: false,
            unique: false,
            options: {
              mimeTypes: ['image/jpeg', 'image/png', 'image/svg+xml', 'image/gif', 'image/webp'],
              thumbs: null,
              maxSelect: 1,
              maxSize: 5242880,
              protected: false,
            },
          },
        ],
        indexes: [],
        listRule: 'id = @request.auth.id',
        viewRule: 'id = @request.auth.id',
        createRule: '',
        updateRule: 'id = @request.auth.id',
        deleteRule: 'id = @request.auth.id',
        options: {
          allowEmailAuth: true,
          allowOAuth2Auth: true,
          allowUsernameAuth: true,
          exceptEmailDomains: null,
          manageRule: null,
          minPasswordLength: 8,
          onlyEmailDomains: null,
          onlyVerified: false,
          requireEmail: false,
        },
      },
      {
        id: 'nlfshqbfbb4wj5w',
        created: '2024-09-13 15:16:15.601Z',
        updated: '2024-09-14 08:36:14.517Z',
        name: 'cities',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: '2ioztylk',
            name: 'name',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'awumm3yj',
            name: 'name_en',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'bhpdezsn',
            name: 'zone',
            type: 'select',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: [
                'גליל עליון',
                'דרום הנגב',
                'שפלת יהודה',
                'מרכז הגליל',
                'מנשה',
                'קו העימות',
                'לכיש',
                'שרון',
                'ירושלים',
                'גולן דרום',
                'שומרון',
                'ים המלח',
                'עוטף עזה',
                'יהודה',
                'גולן צפון',
                'ואדי ערה',
                'העמקים',
                'מרכז הנגב',
                'מערב הנגב',
                'דן',
                'המפרץ',
                'ירקון',
                'מערב לכיש',
                'הכרמל',
                'השפלה',
                'בקעת בית שאן',
                'גליל תחתון',
                'אילת',
                'ערבה',
                'בקעה',
                'שפלת יהודה',
              ],
            },
          },
          {
            system: false,
            id: '4gnrqkbe',
            name: 'zone_en',
            type: 'select',
            required: false,
            presentable: false,
            unique: false,
            options: {
              maxSelect: 1,
              values: [
                'Upper Galilee',
                'South Negev',
                'Shfelat Yehuda',
                'Center Galilee',
                'Menashe',
                'Confrontation Line',
                'Lachish',
                'Sharon',
                'Jerusalem',
                'South Golan',
                'Shomron',
                'Dead Sea',
                'Gaza Envelope',
                'Yehuda',
                'North Golan',
                'Wadi Ara',
                'HaAmakim',
                'Center Negev',
                'West Negev',
                'Dan',
                'HaMifratz',
                'Yarkon',
                'West Lachish',
                'HaCarmel',
                'HaShfela',
                "Beit She'an Valley",
                'Lower Galilee',
                'Eilat',
                'Arava',
                "Bika'a",
                'Shfelat Yehuda',
              ],
            },
          },
        ],
        indexes: ['CREATE UNIQUE INDEX `idx_RCOyX72` ON `cities` (`name_en`)'],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: '1fy7cffe7ngbrqm',
        created: '2024-09-13 15:21:48.490Z',
        updated: '2024-09-13 15:21:48.490Z',
        name: 'subscribers',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'adrwhz8w',
            name: 'chat_id',
            type: 'number',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              noDecimal: true,
            },
          },
          {
            system: false,
            id: 'cxmnlrt1',
            name: 'username',
            type: 'text',
            required: true,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'nffvw8yk',
            name: 'fullname',
            type: 'text',
            required: false,
            presentable: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'btz9wjgg',
            name: 'cities',
            type: 'relation',
            required: false,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'nlfshqbfbb4wj5w',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: null,
              displayFields: null,
            },
          },
        ],
        indexes: [
          'CREATE INDEX `idx_wXgaaKW` ON `subscribers` (`chat_id`)',
          'CREATE INDEX `idx_r121WGc` ON `subscribers` (`cities`)',
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: '28ypd7vo7txbiud',
        created: '2024-09-13 17:29:01.795Z',
        updated: '2024-09-13 20:26:55.081Z',
        name: 'alerts',
        type: 'base',
        system: false,
        schema: [
          {
            system: false,
            id: 'wt4ayg0a',
            name: 'date',
            type: 'text',
            required: true,
            presentable: true,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: '',
            },
          },
          {
            system: false,
            id: 'rq6vxrbj',
            name: 'original_message_url',
            type: 'url',
            required: true,
            presentable: true,
            unique: false,
            options: {
              exceptDomains: [],
              onlyDomains: [],
            },
          },
          {
            system: false,
            id: '6xubktpm',
            name: 'cities',
            type: 'relation',
            required: true,
            presentable: false,
            unique: false,
            options: {
              collectionId: 'nlfshqbfbb4wj5w',
              cascadeDelete: false,
              minSelect: null,
              maxSelect: null,
              displayFields: null,
            },
          },
          {
            system: false,
            id: 'orwacgau',
            name: 'alerted_subscribers',
            type: 'bool',
            required: false,
            presentable: false,
            unique: false,
            options: {},
          },
        ],
        indexes: [],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
    ];

    const collections = snapshot.map(item => new Collection(item));

    return Dao(db).importCollections(collections, true, null);
  },
  db => {
    return null;
  },
);
