name: Invoke build & deploy Production
run-name: Invoke build & deploy Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  invoke-docker-image-ci-and-deploy:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Call Docker Image CI
        uses: actions/github-script@v7
        with:
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'docker-build-images.yml',
              ref: 'main',
              inputs: {
                branch: 'main',
                repo_name: 'red-alert-bot',
                tag: 'latest',
                webhook_coolify: 'true'
              }
            });
            console.log(result);
          github-token: ${{ secrets.GITHUB_TOKEN }}
