name: Docker Image CI
run-name: Build ${{ inputs.branch }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'GitHub branch to create image off.'
        required: true
        default: 'main'
      tag:
        description: 'Name of the docker tag to create.'
        required: true
        default: 'latest'
      webhook_coolify_dev:
        description: 'Dev Coolify webhook after build successfully.'
        required: false
        default: 'false'
      webhook_coolify_prod:
        description: 'Prod Coolify webhook after build successfully.'
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: noamloewenstern
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push "red-alert-bot/apps:${{ github.event.inputs.tag }}" image to ghcr.io
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/noamloewenstern/red-alert-bot/apps:${{ github.event.inputs.tag }}

      - name: Build and push "red-alert-bot/webapp:${{ github.event.inputs.tag }}" image to ghcr.io
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/webapp-miniapp/Dockerfile
          provenance: false
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/noamloewenstern/red-alert-bot/webapp:${{ github.event.inputs.tag }}

      - name: Call Coolify Webhook DEV
        if: ${{ github.event.inputs.webhook_coolify_dev }} == "true"
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_PROD }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
        shell: bash

      - name: Call Coolify Webhook PROD
        if: ${{ github.event.inputs.webhook_coolify_prod }} == "true"
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_DEV }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
        shell: bash
